language: java
before_install: mvn install -DskipTests=true -DfinalName=any23-transformer-$TRAVIS_TAG
deploy:
  edge: true
  provider: releases
  api-key:
    - secure: VWL+B2S6Xixj+actXHzxMJCKeaLVKejyiK88FJEM1+deYJ8rcUGz1PUYMFN2yf5qQShIEuWr3qQrtLq6gxocvGh4peWdPqGMIkjIr+tXTozaGJ+2ogknXyOm0PoxSmHgwXL48H/bEuEjgzqYroBhc0EMjiskI47lJNrmeDq7mtM=
  file: target/any23-transformer-$TRAVIS_TAG.jar
  on:
    tags: true
    all_branches: true
